config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  post '/posts/:post_id/comments', to: 'comments#create', as: :post_comments
  resources :users, :posts, :comments do
    member do
      put 'upvote'
      put 'downvote'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post
    can :show, User
    can :show, Comment
    return unless user.present?
    can :create, Post
    can :index, User
    can :create, Comment
    can [:upvote, :downvote], [Post, Comment, User]
    return unless user.moderator? || user.admin?
    can :manage, Post
    can :manage, Comment
    # TODO Set up differentiation of ability in the activeadmin
    can :read, ActiveAdmin::Page, name: "Dashboard", namespace_name: "moderator"
    return unless user.admin?
    can :manage, :all
    can :manage, ActiveAdmin::Page
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  acts_as_votable
  default_scope -> { order(created_at: :asc) }
  validates :content, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :confirmable, :validatable,
         password_length: 8..70, authentication_keys: [:username]
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  acts_as_votable
  scope :active_users, -> { where('deleted_at IS NULL') }

  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?

  validate :password_complexity
  validates :username, uniqueness: { case_sensitive: false },
                       length: { minimum: 1, maximum: 50 }
  validates :email, uniqueness: { case_sensitive: false }

  extend FriendlyId
  friendly_id :username, use: :slugged

  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  def active_for_authentication?
    super && !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  private

  def password_complexity
    regxp = /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/
    if password && password !~ regxp
      msg = 'must include at least one lowercase letter, one uppercase letter, and one digit'
      errors[:password] << msg
    end
  end

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    if current_user.nil?
      session[:next] = request.fullpath
      redirect_to new_user_session_path, alert: 'You have to log in to continue.'
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  load_and_authorize_resource

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment[:user_id] = current_user.id

    if @comment.save
      redirect_to post_path(@post), notice: 'Comment was successfully created.'
    else
      redirect_to post_path(@post), alert: "Comment can't be blank"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@comment[:post_id]), notice: 'Post was successfully updated.'
    else
      render post_path(@comment[:post_id])
    end
  end

  def destroy
    post = @comment[:post_id]
    @comment.destroy
    redirect_to post_path(post), notice: 'Comment was successfully destroyed.'
  end

  def upvote
    @comment.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @comment.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id, :image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  def index
    @posts = Post.includes(:user).paginate(page: params[:page], per_page: 10)
  end

  def show
    @comments = @post.comments.includes(:user).paginate(page: params[:page])
  end

  def new
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def upvote
    @post.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @post.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :image)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show, :upvote, :downvote]
  load_and_authorize_resource

  def index
    @users = User.active_users.order(:cached_weighted_score => :desc)
                 .includes(:posts, :comments).paginate(page: params[:page])
  end

  def show
    @posts = @user.posts.paginate(page: params[:page], per_page: 10)
    @comments = @user.comments.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @user.soft_delete
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  def upvote
    @user.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @user.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def set_user
    @user = User.friendly.active_users.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= form_with(model: @comment) do |form| %>
  <% if @comment.errors.any? %>
    <div class="alert my-3 p-2 alert-danger">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :content, class: "form-control",  rows: "5" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: "btn btn-light" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
  <nav class="navbar navbar-expand bottom navbar-light bg-light mt-4">
    <div class="container px-3">
      <%= link_to "Reddthis", root_path, class: "navbar-brand mb-0 h1 text-uppercase" %>
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="font-weight-bold">
            <%= link_to 'New post', new_post_path, class: "nav-link"  %>
          </li>
          <li>
            <%= link_to 'Users', users_path, class: "nav-link"  %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class='navbar navbar-expand navbar-light' style='background-color: #e4e4e7;'>
    <%= link_to image_tag('logo.png', alt: 'Reddthis', width: '25', height: '25', class: 'd-inline-block align-top'), root_path %>
    <%= link_to 'eddthis', root_path, class: 'navbar-brand mb-0 h1 text-uppercase' %>
    <% if user_signed_in? %>
      <ul class='navbar-nav ml-auto'>
        <li class='nav-item dropdown'>
          <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            <%= current_user.username %>
          </a>
          <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
            <% if can? :read, ActiveAdmin::Page %>
              <%= link_to 'Admin dashboard', admin_dashboard_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Users', users_path, class: 'dropdown-item' %>
            <%= link_to 'Profile', current_user, class: 'dropdown-item' %>
            <div class='dropdown-divider'></div>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'dropdown-item' %>
          </div>
        </li>
        <li></li>
        <li>
          <%= link_to 'New post', new_post_path, class: 'btn btn-secondary'  %>
        </li>
      </ul>
    <% else %>
      <ul class='navbar-nav ml-auto'>
        <li>
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'Signup', new_user_registration_path, class: 'btn btn-secondary' %>
        </li>
      </ul>
    <% end %>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert my-3 p-2 alert-<%= type.to_s == 'notice' ? 'success' : 'danger' %>">
    <%= content_tag :div, msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Reddthis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body class="d-flex flex-column h-100">
    <%= render 'layouts/header' %>
    <main class="flex-shrink-0">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div class="alert my-3 p-2 alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :content, class: "form-control",  rows: "5" %>
  </div>

  <div class="form-group">
    <%= form.label 'Add image' %><br>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Back", :back, class: "btn btn-light" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render 'shared/posts' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class='mt-3 p-2 bg-light rounded shadow-sm d-flex'>
  <div class='btn-group-vertical btn-group-sm'>
    <%= link_to '+', upvote_post_path(@post), method: :put, remote: true, class: 'badge badge-light w-100' %>
    <span class='badge badge-light w-100'><%= @post.weighted_score %></span>
    <%= link_to '-', downvote_post_path(@post), method: :put, remote: true, class: 'badge badge-light w-100' %>
  </div>
  <div class='mx-2 text-justify'><%= @post.content %></div>
  <% if @post.image? %>
    <%= link_to (image_tag @post.image.small.url), @post.image.url %>
  <% end %>
</div>

<div class='row my-2'>
  <div class='col'>
    <small>
      Posted by <%= link_to @post.user.username, @post.user %>
      <%= time_ago_in_words(@post.created_at) %> ago
    </small>
  </div>
  <% if can? :manage, @post %>
    <div class='col-2'>
      <%= link_to 'delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-light font-weight-light float-right' %>
      <%= link_to 'edit', edit_post_path(@post), class: 'badge badge-light font-weight-light float-right' %>
    </div>
  <% end %>
</div>

<% if @comments.any? %>
  <h5 class='mt-2'>Comments</h5>
  <%= render 'shared/comments' %>
<% end %>

<% if current_user && (can? :create, Comment) %>
  <h5 class='mt-2'>Add comment</h5>
  <%= form_with(model: [@post, @post.comments.build]) do |form| %>

    <div class="form-group">
      <%= form.text_area :content, class: "form-control",  rows: "5" %>
    </div>

    <div class="form-group">
      <%= form.label 'Add image' %><br>
      <%= form.file_field :image %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %> to write a comment
<% end %>

app/views/shared/_comments.html.erb
<% @comments.each do |comment| %>
  <div class='mt-3 p-1 bg-light rounded shadow-sm'>
    <%= comment.content %>
    <%= image_tag comment.image.url if comment.image? %>

    <div class='row'>
      <div class='col-1'>
        <small class='btn-group-vertical btn-group-sm'>
          <%= link_to '+', upvote_comment_path(comment), method: :put, remote: true, class: 'badge badge-light w-100' %>
          <%= link_to '-', downvote_comment_path(comment), method: :put, remote: true, class: 'badge badge-light w-100' %>
        </small>
        <span class='badge badge-light'><%= comment.weighted_score %></span>
      </div>

      <div class='col'>
        <small>
          Posted by <%= link_to comment.user.username, comment.user %>
          <%= time_ago_in_words(comment.created_at) %> ago
        </small>
      </div>

      <% if can? :manage, comment %>
        <div class='col-2 align-self-end'>
          <%= link_to 'delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-light font-weight-light float-right' %>
          <%= link_to 'edit', edit_comment_path(comment), class: 'badge badge-light font-weight-light float-right' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= will_paginate @comments, list_classes: %w(pagination my-3 justify-content-center) %>

app/views/shared/_posts.html.erb
<% @posts.each do |post| %>
  <div class='mt-4 p-1 bg-light rounded shadow-sm w-100'>
    <div class='mx-2 text-justify'>
      <%= link_to post.content, post, class: 'text-decoration-none text-dark' %>
      <% if post.image? %>
        <%= link_to (image_tag post.image.small.url), post.image.url %>
      <% end %>
    </div>
    <div class='row'>
      <div class='col-1'>
        <small class='btn-group-vertical btn-group-sm'>
          <%= link_to '+', upvote_post_path(post), method: :put, remote: true, class: 'badge badge-light w-100' %>
          <%= link_to '-', downvote_post_path(post), method: :put, remote: true, class: 'badge badge-light w-100' %>
        </small>
        <span class='badge badge-light'><%= post.weighted_score %></span>
      </div>
      <div class='col'>
        <small>
          Posted by <%= link_to post.user.username, post.user %>
          <%= time_ago_in_words(post.created_at) %> ago
        </small>
      </div>
      <% if can? :manage, post %>
        <div class='col-2 align-self-end'>
          <%= link_to 'delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-light font-weight-light float-right' %>
          <%= link_to 'edit', edit_post_path(post), class: 'badge badge-light font-weight-light float-right' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= will_paginate @posts, list_classes: %w(pagination my-3 justify-content-center) %>

app/views/users/index.html.erb
<h3 class='text-center'>All users</h3>
<div class='row justify-content-md-center'>
  <div class='list-group col-8'>
    <% @users.each do |user| %>
      <button type='button' class='list-group-item list-group-item-action d-flex justify-content-between align-items-center'>
        <span class='badge badge-secondary badge-pill'>
          <%= user.weighted_score %> carma
        </span>
        <%= link_to user.username, user, class: 'text-decoration-none stretched-link text-wrap' %>
        <span class='badge badge-secondary badge-pill'>
          <%= pluralize(user.posts.size, 'post') %>
          and <%= pluralize(user.comments.size, 'comment') %>
        </span>
      </button>
    <% end %>
  </ul>

  <%= will_paginate list_classes: %w(pagination my-3 justify-content-center) %>
</div>

app/views/users/show.html.erb
<div class='row mt-3'>
  <ul class='nav nav-tabs' id='myTab' role='tablist'>
    <li class='navbar-item'>
      <small class='btn-group-vertical btn-group-sm'>
        <%= link_to '+', upvote_user_path(@user), method: :put, remote: true, class: 'badge badge-light w-100' %>
        <%= link_to '-', downvote_user_path(@user), method: :put, remote: true, class: 'badge badge-light w-100' %>
      </small>
      <span class='badge badge-light'><%= @user.weighted_score %></span>
    </li>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <li class='nav-item'>
      <span class='navbar-brand font-weight-bold'><%= @user.username %></span>
    </li>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <li class='nav-item'>
      <a class='nav-link active' id='posts-tab' data-toggle='tab' href='#posts' role='tab' aria-controls='posts' aria-selected='true'>Posts</a>
    </li>
    <li class='nav-item'>
      <a class='nav-link' id='comments-tab' data-toggle='tab' href='#comments' role='tab' aria-controls='comments' aria-selected='false'>Comments</a>
    </li>
    <li class='nav-item'>
      <% if @user == current_user %>
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link btn btn-outline-secondary' %>
      <% end %>
    </li>
    <li class='nav-item'>
      <% if (can? :manage, @user) && !@user.admin? %>
        <%= link_to 'Delete profile', user_path(@user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'nav-link btn btn-outline-secondary' %>
      <% end %>
    </li>
  </ul>
</div>
<div class='tab-content' id='myTabContent'>
  <div class='tab-pane fade show active' id='posts' role='tabpanel' aria-labelledby='posts-tab'>
    <div class='row'>
      <%= render 'shared/posts' %>
    </div>
  </div>
  <div class='tab-pane fade' id='comments' role='tabpanel' aria-labelledby='comments-tab'>
    <%= render 'shared/comments' %>
  </div>
</div>